# Generated by Django 3.2.12 on 2022-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_event_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
