# Generated by Django 3.2.12 on 2022-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_integration', '0002_event_base_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer_company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
