# Generated by Django 3.2.12 on 2024-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_integration', '0003_auto_20220218_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_datetime',
            new_name='event_start_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
