# Generated by Django 3.2.12 on 2024-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_integration', '0004_auto_20240413_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(),
        ),
    ]
